# Generated by Django 6.0.1 on 2026-01-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField()),
                ('peso_kg', models.FloatField()),
                ('serie_1', models.IntegerField()),
                ('serie_2', models.IntegerField()),
                ('serie_3', models.IntegerField()),
                ('serie_4', models.IntegerField()),
                ('volume_total', models.FloatField()),
                ('data_treino', models.DateField()),
            ],
        ),
    ]
