# Generated by Django 6.0.1 on 2026-01-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='serie_1',
            new_name='first_set_reps',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='serie_2',
            new_name='fourth_set_reps',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='serie_3',
            new_name='second_set_reps',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='serie_4',
            new_name='third_set_reps',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='data_treino',
            new_name='training_day',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='peso_kg',
            new_name='volume_total_weight',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='volume_total',
            new_name='weight_kg',
        ),
    ]
