# Generated by Django 6.0.1 on 2026-01-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_serie_1_training_first_set_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='volume_total_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
