# Generated by Django 6.0.1 on 2026-01-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_volume_total_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_day',
            new_name='training_date',
        ),
    ]
