# Generated by Django 6.0.1 on 2026-02-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_rename_training_day_training_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercise_id',
            field=models.UUIDField(),
        ),
    ]
