# Generated by Django 6.0.1 on 2026-02-08 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_training_exercise_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_exercise_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('muscle_group', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(max_length=150)),
            ],
        ),
    ]
