from django.db import migrations
import uuid


def seed_exercises(apps, schema_editor):
    Exercise = apps.get_model("training", "Exercise")

    exercises = [
        ("Peito - Superior", "Supino inclinado barra"),
        ("Peito - Superior", "Supino inclinado halteres"),
        ("Peito - Superior", "Supino inclinado Smith"),
        ("Peito - Superior", "Supino inclinado máquina"),
        ("Peito - Superior", "Crucifixo inclinado halteres"),
        ("Peito - Superior", "Crucifixo inclinado polia"),
        ("Peito - Superior", "Crossover baixo (polia baixa subindo)"),
        ("Peito - Superior", "Flexão inclinada (mãos elevadas)"),
        ("Peito - Superior", "Press inclinado na polia (cabo)"),
        ("Peito - Superior", "Chest press inclinado máquina"),
        ("Peito - Meio", "Supino reto barra"),
        ("Peito - Meio", "Supino reto halteres"),
        ("Peito - Meio", "Supino reto Smith"),
        ("Peito - Meio", "Chest press máquina"),
        ("Peito - Meio", "Supino reto máquina articulada"),
        ("Peito - Meio", "Crucifixo reto halteres"),
        ("Peito - Meio", "Crucifixo reto polia"),
        ("Peito - Meio", "Peck deck (voador)"),
        ("Peito - Meio", "Flexão tradicional"),
        ("Peito - Meio", "Press reto na polia"),
        ("Peito - Meio", "Flexão com pegada aberta"),
        ("Peito - Meio", "Flexão com peso (anilha/mochila)"),
        ("Peito - Inferior", "Supino declinado barra"),
        ("Peito - Inferior", "Supino declinado halteres"),
        ("Peito - Inferior", "Supino declinado Smith"),
        ("Peito - Inferior", "Chest press declinado máquina"),
        ("Peito - Inferior", "Crossover alto (polia alta descendo)"),
        ("Peito - Inferior", "Crucifixo declinado halteres"),
        ("Peito - Inferior", "Mergulho em paralelas (foco peito)"),
        ("Peito - Inferior", "Flexão declinada (pés elevados)"),
        ("Peito - Inferior", "Press declinado polia"),
        ("Costas - Dorsal (largura)", "Barra fixa pronada"),
        ("Costas - Dorsal (largura)", "Barra fixa supinada"),
        ("Costas - Dorsal (largura)", "Barra fixa neutra"),
        ("Costas - Dorsal (largura)", "Puxada aberta frente"),
        ("Costas - Dorsal (largura)", "Puxada aberta máquina"),
        ("Costas - Dorsal (largura)", "Puxada supinada"),
        ("Costas - Dorsal (largura)", "Puxada neutra"),
        ("Costas - Dorsal (largura)", "Puxada unilateral polia"),
        ("Costas - Dorsal (largura)", "Puxada articulada máquina"),
        ("Costas - Dorsal (largura)", "Pulldown com braços estendidos"),
        ("Costas - Dorsal (largura)", "Pullover máquina"),
        ("Costas - Dorsal (largura)", "Pullover com halter"),
        ("Costas - Meio (espessura)", "Remada curvada barra"),
        ("Costas - Meio (espessura)", "Remada curvada pegada supinada"),
        ("Costas - Meio (espessura)", "Remada unilateral halter"),
        ("Costas - Meio (espessura)", "Remada serrote"),
        ("Costas - Meio (espessura)", "Remada baixa polia"),
        ("Costas - Meio (espessura)", "Remada baixa triângulo"),
        ("Costas - Meio (espessura)", "Remada máquina articulada"),
        ("Costas - Meio (espessura)", "Remada cavalinho (T-bar)"),
        ("Costas - Meio (espessura)", "Remada cavalinho máquina"),
        ("Costas - Meio (espessura)", "Remada sentado máquina"),
        ("Costas - Meio (espessura)", "Remada no Smith"),
        ("Costas - Meio (espessura)", "Remada invertida (barra fixa baixa)"),
        ("Costas - Meio (espessura)", "Remada com elástico"),
        ("Costas - Trapézio (costas)", "Remada alta barra"),
        ("Costas - Trapézio (costas)", "Remada alta polia"),
        ("Costas - Trapézio (costas)", "Encolhimento barra"),
        ("Costas - Trapézio (costas)", "Encolhimento halteres"),
        ("Costas - Trapézio (costas)", "Encolhimento máquina"),
        ("Costas - Trapézio (costas)", "Encolhimento polia"),
        ("Costas - Lombar", "Levantamento terra"),
        ("Costas - Lombar", "Terra sumô"),
        ("Costas - Lombar", "Terra rack pull"),
        ("Costas - Lombar", "Terra com trap bar"),
        ("Costas - Lombar", "Good morning"),
        ("Costas - Lombar", "Hiperextensão lombar"),
        ("Costas - Lombar", "Extensão lombar máquina"),
        ("Costas - Lombar", "Stiff"),
        ("Costas - Lombar", "Superman (solo)"),
        ("Ombros - Frontal", "Desenvolvimento militar barra"),
        ("Ombros - Frontal", "Desenvolvimento militar halteres"),
        ("Ombros - Frontal", "Desenvolvimento Arnold"),
        ("Ombros - Frontal", "Desenvolvimento máquina"),
        ("Ombros - Frontal", "Desenvolvimento Smith"),
        ("Ombros - Frontal", "Elevação frontal halteres"),
        ("Ombros - Frontal", "Elevação frontal barra"),
        ("Ombros - Frontal", "Elevação frontal polia"),
        ("Ombros - Frontal", "Elevação frontal anilha"),
        ("Ombros - Frontal", "Press ombro polia"),
        ("Ombros - Lateral", "Elevação lateral halteres"),
        ("Ombros - Lateral", "Elevação lateral sentado"),
        ("Ombros - Lateral", "Elevação lateral inclinada"),
        ("Ombros - Lateral", "Elevação lateral polia"),
        ("Ombros - Lateral", "Elevação lateral unilateral polia"),
        ("Ombros - Lateral", "Elevação lateral máquina"),
        ("Ombros - Lateral", "Elevação lateral no cabo por trás"),
        ("Ombros - Lateral", "Remada alta pegada aberta"),
        ("Ombros - Lateral", "Remada alta máquina"),
        ("Ombros - Posterior", "Crucifixo inverso halteres"),
        ("Ombros - Posterior", "Crucifixo inverso máquina"),
        ("Ombros - Posterior", "Crucifixo inverso polia"),
        ("Ombros - Posterior", "Face pull"),
        ("Ombros - Posterior", "Remada alta para posterior (pegada aberta)"),
        ("Ombros - Posterior", "Remada curvada para posterior"),
        ("Ombros - Posterior", "Reverse fly inclinado"),
        ("Ombros - Posterior", "Rear delt row (remada focada posterior)"),
        ("Trapézio", "Encolhimento barra"),
        ("Trapézio", "Encolhimento halteres"),
        ("Trapézio", "Encolhimento máquina"),
        ("Trapézio", "Encolhimento polia"),
        ("Trapézio", "Farmer walk (caminhada com halteres)"),
        ("Trapézio", "Remada alta barra"),
        ("Trapézio", "Remada alta polia"),
        ("Bíceps", "Rosca direta barra"),
        ("Bíceps", "Rosca direta halteres"),
        ("Bíceps", "Rosca direta polia"),
        ("Bíceps", "Rosca alternada"),
        ("Bíceps", "Rosca alternada banco inclinado"),
        ("Bíceps", "Rosca concentrada"),
        ("Bíceps", "Rosca Scott barra W"),
        ("Bíceps", "Rosca Scott máquina"),
        ("Bíceps", "Rosca Scott polia"),
        ("Bíceps", "Rosca 21 barra"),
        ("Bíceps", "Rosca 21 polia"),
        ("Bíceps", "Rosca com pegada fechada"),
        ("Bíceps", "Rosca martelo"),
        ("Bíceps", "Rosca martelo polia"),
        ("Bíceps", "Rosca martelo cruzada"),
        ("Bíceps", "Rosca martelo corda"),
        ("Bíceps", "Rosca inversa barra"),
        ("Bíceps", "Rosca inversa polia"),
        ("Tríceps", "Tríceps corda"),
        ("Tríceps", "Tríceps barra reta"),
        ("Tríceps", "Tríceps barra V"),
        ("Tríceps", "Tríceps unilateral polia"),
        ("Tríceps", "Tríceps testa barra W"),
        ("Tríceps", "Tríceps testa halteres"),
        ("Tríceps", "Tríceps testa polia"),
        ("Tríceps", "Tríceps francês halter"),
        ("Tríceps", "Tríceps francês polia"),
        ("Tríceps", "Tríceps acima da cabeça corda"),
        ("Tríceps", "Tríceps banco (mergulho)"),
        ("Tríceps", "Mergulho paralelas (foco tríceps)"),
        ("Tríceps", "Tríceps coice halteres"),
        ("Tríceps", "Tríceps coice polia"),
        ("Tríceps", "Tríceps máquina"),
        ("Tríceps", "Supino fechado"),
        ("Tríceps", "Flexão diamante"),
        ("Inferiores - Quadríceps", "Agachamento livre"),
        ("Inferiores - Quadríceps", "Agachamento frontal"),
        ("Inferiores - Quadríceps", "Agachamento Smith"),
        ("Inferiores - Quadríceps", "Agachamento Hack"),
        ("Inferiores - Quadríceps", "Hack squat máquina"),
        ("Inferiores - Quadríceps", "Leg press 45°"),
        ("Inferiores - Quadríceps", "Leg press horizontal"),
        ("Inferiores - Quadríceps", "Leg press unilateral"),
        ("Inferiores - Quadríceps", "Cadeira extensora"),
        ("Inferiores - Quadríceps", "Afundo com halteres"),
        ("Inferiores - Quadríceps", "Afundo no Smith"),
        ("Inferiores - Quadríceps", "Passada andando"),
        ("Inferiores - Quadríceps", "Passada estacionária"),
        ("Inferiores - Quadríceps", "Passada no step"),
        ("Inferiores - Quadríceps", "Agachamento búlgaro"),
        ("Inferiores - Quadríceps", "Sissy squat"),
        ("Inferiores - Quadríceps", "Step-up com halteres"),
        ("Inferiores - Posterior de Coxa", "Stiff barra"),
        ("Inferiores - Posterior de Coxa", "Stiff halteres"),
        ("Inferiores - Posterior de Coxa", "Terra romeno"),
        ("Inferiores - Posterior de Coxa", "Mesa flexora deitada"),
        ("Inferiores - Posterior de Coxa", "Mesa flexora unilateral"),
        ("Inferiores - Posterior de Coxa", "Flexora sentado"),
        ("Inferiores - Posterior de Coxa", "Flexora em pé"),
        ("Inferiores - Posterior de Coxa", "Flexão nórdica (Nordic curl)"),
        ("Inferiores - Posterior de Coxa", "Good morning"),
        ("Inferiores - Posterior de Coxa", "Glute ham raise"),
        ("Inferiores - Posterior de Coxa", "Pull-through na polia"),
        ("Inferiores - Glúteo", "Elevação pélvica barra"),
        ("Inferiores - Glúteo", "Elevação pélvica máquina"),
        ("Inferiores - Glúteo", "Ponte de glúteo (solo)"),
        ("Inferiores - Glúteo", "Agachamento sumô"),
        ("Inferiores - Glúteo", "Leg press com foco glúteo"),
        ("Inferiores - Glúteo", "Afundo"),
        ("Inferiores - Glúteo", "Passada"),
        ("Inferiores - Glúteo", "Búlgaro"),
        ("Inferiores - Glúteo", "Coice na polia"),
        ("Inferiores - Glúteo", "Coice na máquina"),
        ("Inferiores - Glúteo", "Abdução de quadril máquina"),
        ("Inferiores - Glúteo", "Abdução de quadril polia"),
        ("Inferiores - Glúteo", "Cadeira abdutora"),
        ("Inferiores - Glúteo", "Kickback com elástico"),
        ("Inferiores - Glúteo", "Step-up"),
        ("Inferiores - Glúteo", "Deadlift sumô"),
        ("Inferiores - Glúteo", "Pull-through polia"),
        ("Inferiores - Adutores/Abdutores", "Cadeira adutora"),
        ("Inferiores - Adutores/Abdutores", "Cadeira abdutora"),
        ("Inferiores - Adutores/Abdutores", "Adutor na polia"),
        ("Inferiores - Adutores/Abdutores", "Abdutor na polia"),
        ("Inferiores - Adutores/Abdutores", "Agachamento sumô"),
        ("Inferiores - Adutores/Abdutores", "Passada lateral"),
        ("Panturrilha", "Panturrilha em pé máquina"),
        ("Panturrilha", "Panturrilha sentado máquina"),
        ("Panturrilha", "Panturrilha no leg press"),
        ("Panturrilha", "Panturrilha em pé com barra"),
        ("Panturrilha", "Panturrilha em pé com halteres"),
        ("Panturrilha", "Panturrilha unilateral com halter"),
        ("Panturrilha", "Panturrilha no Smith"),
        ("Panturrilha", "Panturrilha na polia"),
        ("Panturrilha", "Panturrilha no degrau"),
        ("Panturrilha", "Panturrilha sentado com halter no joelho"),
    ]

    for muscle_group, exercise_name in exercises:
        Exercise.objects.get_or_create(
            muscle_group=muscle_group,
            exercise_name=exercise_name,
            defaults={"uuid_exercise_id": uuid.uuid4()}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_exercises),
    ]
