# Generated by Django 6.0.1 on 2026-02-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_exercise'),
        ('training', '0007_seed_exercises'),
    ]

    operations = [
    ]
